# lista = ["rh3software.com",
# "www.basecinco.com",
# "www.pitang.com",
# "kuriertecnologia.com.br",
# "orubetecnologia.com.br",
# "www.incorptech.com.br",
# "www.educandus.com.br",
# "www.inforpartner.com.br",
# "www.mabuya.tech",
# "suportegerencial.com.br",
# "www.inforio.com.br",
# "www.maturicomunicacao.com",
# "cmtech.com.br",
# "www.sigrasoftware.com",
# "www.vc2.com.br",
# "www.manifestogames.com.br",
# "www.serttel.com.br",
# "www.inhalt.com.br",
# "www.vectracs.com",
# "www.ivia.com.br",
# "www.corptech.com.br",
# "www.smart.net.br",
# "tributosmunicipais.com.br",
# "www.gcinet.com.br",
# "www.swquality.com.br",
# "www.dialoga.com.br",
# "www.neurotech.com.br",
# "www.procenge.com.br",
# "www.libro.studio",
# "bemind.com.br",
# "www.bisaweb.com.br",
# "www.tecsolucoesti.com.br",
# "www.athiva.com.br",
# "www.ncti.com.br",
# "partecweb.com.br",
# "www.preservtec.com.br",
# "www.taurustech.com.br",
# "www.grupoteleport.com.br",
# "www.elcoma.com.br",
# "www.phoebus.com.br",
# "www.midiavox.com.br",
# "facilit.com.br",
# "qualinfo.com.br",
# "www.locaweb.com.br",
# "www.informa.com.br",
# "www.cittati.com.br",
# "www.labdesign.com.br",
# "www.emprel.gov.br",
# "sodet.biz",
# "www.implystudio.com",
# "www.ribeirocavalcanti.com.br",
# "www.infox.com.br",
# "www.raidhut.com",
# "www.muma.com.br",
# "www.urjasocial.com.br",
# "www.joystreet.com.br"]

documento_empresas = {}

def get_dict_documento_empresa():
    with open("Empresa-documento.csv","r") as arquivo:
        for linha in arquivo:
            site = linha.split(',')[1]
            nome = linha.split(',')[0]
            documento_empresas[site] = nome
    return documento_empresas
